version: "3.7"
services:

  postgres:
    image: postgres:14.7
    env_file:
      - ./config/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d employees_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  app:
    restart: unless-stopped
    build:
      context: .
    env_file:
      - ./config/.env
    environment:
      - PYTHONPATH=.
      - PYTHONIOENCODING=utf8
    ports:
      - '80:8080'
    depends_on:
      - postgres
